---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.application.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.application.ingress.path | quote }}
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: {{ .Values.backend.port }}
  tls:
    - hosts:
        - {{ .Values.application.ingress.host }}
      secretName: cloudflare-tls
