---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.application.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: {{ .Values.backend.port }}
          - pathType: Prefix
            path: "/"
            backend:
              serviceName: {{ .Release.Name }}-frontend
              servicePort: {{ .Values.frontend.port }}
  tls:
    - hosts:
        - {{ .Values.application.host }}
      secretName: cloudflare-tls
