---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret-tokens
type: Opaque
stringData:
    jwt-secret: "{{ .Values.application.secrets.jwtSecret }}"
    uuid-namespace: "{{ .Values.application.secrets.uuidNamespace }}"
    aws-access-key-id: "{{ .Values.application.secrets.awsAccessKeyId }}"
    aws-secret-access-key: "{{ .Values.application.secrets.awsSecretAccessKey }}"
    sentry-url: "{{ .Values.application.secrets.sentryUrl }}"
---
# https://dev.to/asizikov/using-github-container-registry-with-kubernetes-38fb
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
data:
  .dockerconfigjson: "{{ .Values.application.secrets.dockerConfigJson }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tls
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.application.secrets.tlsCrt }}"
  tls.key: "{{ .Values.application.secrets.tlsKey }}"
