application:
  host: pennbook.app

jobs:
  - name: load-data
    schedule: "0 0 31 2 *" # never execute (only run manually)
    command: '["npm"]'
    args: '["run", "load-data"]'
  - name: recommend-articles
    schedule: "0 * * * *"
    command: '["npm"]'
    args: '["run", "recommend-articles"]'

redis:
  image: redis
  tag: "6.2"
  port: 6379
  replicas: 1

backend:
  image: ghcr.io/mureytasroc/pennbook/backend
  port: 8000
  replicas: 1

frontend:
  image: ghcr.io/mureytasroc/pennbook/frontend
  port: 3000
  replicas: 1
