application:
  host: pennbook.app

recommendArticlesJob:
  schedule: "15 5 * * *"

redis:
  image: redis
  tag: "6.0"
  port: 6379
  replicas: 1

backend:
  image: ghcr.io/mureytasroc/pennbook/backend
  port: 8000
  replicas: 1

frontend:
  image: ghcr.io/mureytasroc/pennbook/frontend
  port: 3000
  replicas: 1
