apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret-tokens
type: Opaque
stringData:
    jwt: {{ .Values.application.secrets.jwt }}
    uuid-namespace: {{ .Values.application.secrets.uuid-namespace }}
