apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret-tokens
type: Opaque
stringData:
    jwt: {{ .Values.application.secrets.jwt }}
    uuid-namespace: {{ .Values.application.secrets.uuid-namespace }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
data:
  .dockerconfigjson: {{ .Values.application.secrets.docker-config-json }}
