---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Release.Name }}-frontend
      port:
        number: {{ .Values.frontend.port }}
  rules:
    - host: {{ .Values.application.host }}
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: "/socket.io"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.port }}
  tls:
    - hosts:
        - {{ .Values.application.host }}
      secretName: cloudflare-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-spark-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: admin-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
    - host: "spark.{{ .Values.application.host }}"
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: spark-recommend-articles-ui-svc
                port:
                  number: 4040
  tls:
    - hosts:
        - "spark.{{ .Values.application.host }}"
      secretName: cloudflare-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-k8s-ingress
  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
    - host: "k8s.{{ .Values.application.host }}"
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
  tls:
    - hosts:
        - "k8s.{{ .Values.application.host }}"
      secretName: cloudflare-tls
