---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-ml
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-ml
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-ml
        spec:
            containers:
                - name: {{ .Release.Name }}-ml
                  image: '{{ .Values.ml.image }}:{{ .Values.application.gitSHA }}'
                  ports:
                      - containerPort: {{ .Values.ml.port }}

            imagePullSecrets:
                - name: {{ .Release.Name }}-dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-ml
spec:
    selector:
        app: {{ .Release.Name }}-ml
    ports:
        - port: {{ .Values.ml.port }}
