grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.pennbook.app
    tls:
      - hosts:
          - grafana.pennbook.app
        secretName: cloudflare-tls

  admin:
    existingSecret: grafana

  persistence:
    enabled: true
    type: statefulset
    size: 10Gi

  plugins:
    - grafana-piechart-panel

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter:
        gnetId: 1860
        revision: 19
      pod-dashboard:
        url: https://raw.githubusercontent.com/pennlabs/infrastructure/master/grafana-dashboards/pod-dashboard.json

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring
          access: proxy
          orgId: 1

  grafana.ini:
    server:
      domain: "grafana.pennbook.app"
      root_url: "https://%(domain)s/"

  envFromSecret: "grafana"
