apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-recommend-articles
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: ghcr.io/mureytasroc/pennbook/spark:TODO
  imagePullSecrets:
    - name: pennbook-dockerconfigjson-github-com
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/sparkapps/recommend-articles.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    env:
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: pennbook-secret-tokens
            key: aws-access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: pennbook-secret-tokens
            key: aws-secret-access-key
  executor:
    cores: 1
    instances: 5
    memory: "512m"
    labels:
      version: 3.1.1
