aws:
  region: us-east-1

application:
  ingress:
    host: pennbook.app
    path: "/"
    secretName: "pennbook-cert"
  secrets:
    jwt: TODO (github actions)
    uuid-namespace: TODO (github actions)
    docker-config-json: TODO (github actions)

recommend-articles-job:
  schedule: "0 3 * * *"

redis:
  image: redis
  tag: "6.0"
  port: 6379
  replicas: 1

backend:
  image: ghcr.io/mureytasroc/pennbook/backend
  tag: v2
  port: 8000
  replicas: 1
