name: PennBook
on: push

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm install
      - run: npm run lint

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm install
      - run: npm test
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

  build:
    name: Build and publish backend
    runs-on: ubuntu-latest
    needs:
      - lint
      - backend-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/mureytasroc/pennbook/backend:${{ github.sha }}

  deploy:
    name: Deploy latest version of code
    if: github.ref == 'refs/heads/master'
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy code
        run: >-
          cd k8s

          aws eks --region us-east-1 update-kubeconfig --name pennbook-cluster

          kubectl config set-context --current --namespace=default

          helm upgrade --install --atomic pennbook ./pennbook-chart --timeout=10m
          --set application.secrets.jwtSecret=${{ secrets.JWT_SECRET }},application.secrets.uuidNamespace=${{ secrets.UUID_NAMESPACE }}
          --set application.secrets.dockerConfigJson=${{ secrets.DOCKER_CONFIG_JSON }}
          --set application.secrets.cloudflareApiKey=${{ secrets.CLOUDFLARE_API_KEY }},application.secrets.cloudflareApiEmail=${{ secrets.CLOUDFLARE_API_EMAIL }}
          --set application.secrets.traefikAdminCreds=${{ secrets.TRAEFIK_ADMIN_CREDS }}
          --set application.secrets.awsAccessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }},application.secrets.awsSecretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --set application.secrets.sentryUrl=${{ secrets.SENTRY_URL }}
          --set backend.tag=${{ github.sha }}

          kubectl config set-context --current --namespace=traefik

          helm upgrade --install --atomic traefik traefik --namespace=traefik --repo=https://helm.traefik.io/traefik --values=traefik-chart-values.yaml
